# Week 1 Homework - Basics of Neural Network

Welcome to Coding with Lucy! Before we do any hands-on projects, let's get to know the popular python library Numpy first. This tutorial will teach you the basics of working with numpy, as well as some useful neural network techniques, so that in the future, you can easily process data for your neural network. Let's get started!

## 1. Import Libraries

Before we start, let's import a few libraries. If you're getting the error: "No module named 'numpy'", then run:
```
pip install numpy
```

In [21]:
import numpy as np
import math

Now that we've imported numpy, we can access its functions.
We're going to take a look at some basic functions first:

## 2. Sigmoid and Numpy

In [22]:
def basic_sigmoid(x):
    """
    Compute sigmoid of x. (You may need to search this up)

    Arguments:
    x -- A scalar

    Return:
    s -- sigmoid(x)
    """
    
    ### START CODE HERE ### (≈ 1 line of code)
    s = None
    ### END CODE HERE ###
    
    return s

In [23]:
basic_sigmoid(3)

Your output should be 0.9525741268224334
But this only works for 1 number. With machine learning, you will process multiple values together (vectorization), so use the numpy library instead:

In [24]:
def sigmoid(x):
    """
    Compute the sigmoid of x

    Arguments:
    x -- A scalar or numpy array of any size

    Return:
    s -- sigmoid(x)
    """
    
    ### START CODE HERE ### (≈ 1 line of code)
    s = 1 / (1 + np.exp(-x))
    ### END CODE HERE ###
    
    return s

In [25]:
x = np.array([1, 2, 3])
x = sigmoid(x)
print(x)

[0.73105858 0.88079708 0.95257413]


Your output should be:
```
[0.73105858 0.88079708 0.95257413]
```

## 3. Numpy Arrays

You're probably familiar with normal python lists or arrays. Numpy arrays make multi-dimensional arrays a lot easier to work with. This array class is called the "ndarray". Let's define an array:

In [26]:
my_array = np.arange(10)
print(my_array)

[0 1 2 3 4 5 6 7 8 9]


So we created an array of the integers 1 to 10. Next, let's reshape the array:

In [10]:
my_array = my_array.reshape(2, 5)
print(my_array)

[[0 1 2 3 4]
 [5 6 7 8 9]]


So now we have an array of shape (2, 5). These are also sometimes called matrices. If you are unfamiliar with this, then take a look at [this tutorial](https://www.khanacademy.org/math/precalculus/x9e81a4f98389efdf:matrices/x9e81a4f98389efdf:mat-intro/v/introduction-to-the-matrix). Try it out yourself!

In [22]:
def create_an_array():
    # Your take is to create a numpy array of 10 - 23
    # Next, reshape you array to size (2, 7)
    ### START CODE HERE ### ~3 lines
    my_array = None
    return my_array
    ### END CODE HERE ###

In [23]:
check = create_an_array()
print(check)

None


The output should be:
```
[[10 11 12 13 14 15 16]
 [17 18 19 20 21 22 23]]
```

Some other important functions to know include:

In [11]:
print(my_array.shape) #returns the shape of the array
print(my_array.ndim)  #returns the dimension of the array
print(my_array.dtype.name)  #returns the type of value in the array (most commonly int or float)
print(type(my_array)) #returns the type of my_array

(2, 5)
2
int64
<class 'numpy.ndarray'>


You can also convert a python list into a numpy array:

In [14]:
my_list = [[1, 2, 3, 4, 5], [2, 3, 4, 5, 6]]
print(my_list)
print()
my_np_list = np.array(my_list)
print(my_np_list)

[[1, 2, 3, 4, 5], [2, 3, 4, 5, 6]]

[[1 2 3 4 5]
 [2 3 4 5 6]]


One last thing, you can also create an array of zeros

In [15]:
zero = np.zeros((2, 3)) #(2, 3) is the dimensions, so don't forget the extra brackets!
print(zero)

[[0. 0. 0.]
 [0. 0. 0.]]


### 4. Vectorization

In deep learning, you will have a huge, huge dataset, so looping over each individual training example is very slow and inefficient. To solve this, we will use vectorization. Run the following code to see the difference. This code was taken from [deeplearning.ai](https://www.deeplearning.ai/)'s deep learning specialization course 1.

In [17]:
import time

x1 = [9, 2, 5, 0, 0, 7, 5, 0, 0, 0, 9, 2, 5, 0, 0]
x2 = [9, 2, 2, 9, 0, 9, 2, 5, 0, 0, 9, 2, 5, 0, 0]

### CLASSIC DOT PRODUCT OF VECTORS IMPLEMENTATION ###
tic = time.process_time()
dot = 0
for i in range(len(x1)):
    dot+= x1[i]*x2[i]
toc = time.process_time()
print ("dot = " + str(dot) + "\n ----- Computation time = " + str(1000*(toc - tic)) + "ms")

### CLASSIC OUTER PRODUCT IMPLEMENTATION ###
tic = time.process_time()
outer = np.zeros((len(x1),len(x2))) # we create a len(x1)*len(x2) matrix with only zeros
for i in range(len(x1)):
    for j in range(len(x2)):
        outer[i,j] = x1[i]*x2[j]
toc = time.process_time()
print ("outer = " + str(outer) + "\n ----- Computation time = " + str(1000*(toc - tic)) + "ms")
### CLASSIC ELEMENTWISE IMPLEMENTATION ###
tic = time.process_time()
mul = np.zeros(len(x1))
for i in range(len(x1)):
    mul[i] = x1[i]*x2[i]
toc = time.process_time()
print ("elementwise multiplication = " + str(mul) + "\n ----- Computation time = " + str(1000*(toc - tic)) + "ms")

### CLASSIC GENERAL DOT PRODUCT IMPLEMENTATION ###
W = np.random.rand(3,len(x1)) # Random 3*len(x1) numpy array
tic = time.process_time()
gdot = np.zeros(W.shape[0])
for i in range(W.shape[0]):
    for j in range(len(x1)):
        gdot[i] += W[i,j]*x1[j]
toc = time.process_time()
print ("gdot = " + str(gdot) + "\n ----- Computation time = " + str(1000*(toc - tic)) + "ms")

dot = 278
 ----- Computation time = 0.1660000000001105ms
outer = [[81. 18. 18. 81.  0. 81. 18. 45.  0.  0. 81. 18. 45.  0.  0.]
 [18.  4.  4. 18.  0. 18.  4. 10.  0.  0. 18.  4. 10.  0.  0.]
 [45. 10. 10. 45.  0. 45. 10. 25.  0.  0. 45. 10. 25.  0.  0.]
 [ 0.  0.  0.  0.  0.  0.  0.  0.  0.  0.  0.  0.  0.  0.  0.]
 [ 0.  0.  0.  0.  0.  0.  0.  0.  0.  0.  0.  0.  0.  0.  0.]
 [63. 14. 14. 63.  0. 63. 14. 35.  0.  0. 63. 14. 35.  0.  0.]
 [45. 10. 10. 45.  0. 45. 10. 25.  0.  0. 45. 10. 25.  0.  0.]
 [ 0.  0.  0.  0.  0.  0.  0.  0.  0.  0.  0.  0.  0.  0.  0.]
 [ 0.  0.  0.  0.  0.  0.  0.  0.  0.  0.  0.  0.  0.  0.  0.]
 [ 0.  0.  0.  0.  0.  0.  0.  0.  0.  0.  0.  0.  0.  0.  0.]
 [81. 18. 18. 81.  0. 81. 18. 45.  0.  0. 81. 18. 45.  0.  0.]
 [18.  4.  4. 18.  0. 18.  4. 10.  0.  0. 18.  4. 10.  0.  0.]
 [45. 10. 10. 45.  0. 45. 10. 25.  0.  0. 45. 10. 25.  0.  0.]
 [ 0.  0.  0.  0.  0.  0.  0.  0.  0.  0.  0.  0.  0.  0.  0.]
 [ 0.  0.  0.  0.  0.  0.  0.  0.  0.  0.  0.  0.  0.

In [18]:
x1 = [9, 2, 5, 0, 0, 7, 5, 0, 0, 0, 9, 2, 5, 0, 0]
x2 = [9, 2, 2, 9, 0, 9, 2, 5, 0, 0, 9, 2, 5, 0, 0]

### VECTORIZED DOT PRODUCT OF VECTORS ###
tic = time.process_time()
dot = np.dot(x1,x2)
toc = time.process_time()
print ("dot = " + str(dot) + "\n ----- Computation time = " + str(1000*(toc - tic)) + "ms")

### VECTORIZED OUTER PRODUCT ###
tic = time.process_time()
outer = np.outer(x1,x2)
toc = time.process_time()
print ("outer = " + str(outer) + "\n ----- Computation time = " + str(1000*(toc - tic)) + "ms")

### VECTORIZED ELEMENTWISE MULTIPLICATION ###
tic = time.process_time()
mul = np.multiply(x1,x2)
toc = time.process_time()
print ("elementwise multiplication = " + str(mul) + "\n ----- Computation time = " + str(1000*(toc - tic)) + "ms")

### VECTORIZED GENERAL DOT PRODUCT ###
tic = time.process_time()
dot = np.dot(W,x1)
toc = time.process_time()
print ("gdot = " + str(dot) + "\n ----- Computation time = " + str(1000*(toc - tic)) + "ms")


dot = 278
 ----- Computation time = 0.1980000000001425ms
outer = [[81 18 18 81  0 81 18 45  0  0 81 18 45  0  0]
 [18  4  4 18  0 18  4 10  0  0 18  4 10  0  0]
 [45 10 10 45  0 45 10 25  0  0 45 10 25  0  0]
 [ 0  0  0  0  0  0  0  0  0  0  0  0  0  0  0]
 [ 0  0  0  0  0  0  0  0  0  0  0  0  0  0  0]
 [63 14 14 63  0 63 14 35  0  0 63 14 35  0  0]
 [45 10 10 45  0 45 10 25  0  0 45 10 25  0  0]
 [ 0  0  0  0  0  0  0  0  0  0  0  0  0  0  0]
 [ 0  0  0  0  0  0  0  0  0  0  0  0  0  0  0]
 [ 0  0  0  0  0  0  0  0  0  0  0  0  0  0  0]
 [81 18 18 81  0 81 18 45  0  0 81 18 45  0  0]
 [18  4  4 18  0 18  4 10  0  0 18  4 10  0  0]
 [45 10 10 45  0 45 10 25  0  0 45 10 25  0  0]
 [ 0  0  0  0  0  0  0  0  0  0  0  0  0  0  0]
 [ 0  0  0  0  0  0  0  0  0  0  0  0  0  0  0]]
 ----- Computation time = 0.17800000000001148ms
elementwise multiplication = [81  4 10  0  0 63 10  0  0  0 81  4 25  0  0]
 ----- Computation time = 0.12400000000001299ms
gdot = [24.37388714 20.19365471 23.3842404

Please note that np.dot() and np.multiply() are different. If you are unfamiliar with this, then take a look at listed above ([this tutorial](https://www.khanacademy.org/math/precalculus/x9e81a4f98389efdf:matrices/x9e81a4f98389efdf:mat-intro/v/introduction-to-the-matrix)).

And that's it for this tutorial! Hopefully you now know a bit more about neural networks and Numpy now! If you ever forget or need a new function, read the [docs](https://docs.scipy.org/doc/numpy/user/quickstart.html).