# Convolutional Neural Networks
Welcome! In this notebook, we will explore the different components of convolutional neural networks (or convnets).

## 1. Import Libraries
First things first, let's import the basic libaries

In [ ]:
import numpy as np
import matplotlib.pyplot as plt
import tensorflow as tf
from PIL import Image

## 2. The Components
For convnets, there are a few basic layers: the convolutional layer and the max pool layer. To break it down further, we padd the image before the conv layer, then we define a conv "window", then we do the actual forward pass.

## 3. Convolutional Layer
### 3.1 Zero Padding
Without further to do, let's get started! So an image can be converted into a numpy array like so:

![watermelon](watermelon.jpeg)

In [ ]:
image = Image.open('watermelon.jpeg')
my_np_image = np.array(image)
print(my_np_image)

And what we mean by padding is simply adding a layer of 0's around the image, so that we don't loose "valuable" information on the edges.
You can use the function ```np.pad()```

In [ ]:
def zero_pad(image, pad):
    padded = None
    return padded

In [ ]:
np.random.seed(2019)
my_image = np.random.randn(3, 2, 2, 2)
padded_image = zero_pad(my_image, 2)
print(my_image.shape)
print(padded_image.shape)
print(my_image[1][1])
print(padded_image[1][1])

fig, axarr = plt.subplots(1,2)
axarr[0].set_title('my_image')
axarr[0].imshow(my_image[1,:,:,1])
axarr[1].set_title('padded_image')
axarr[1].imshow(padded_image[1,:,:,1])

Your output should be:
```
(3, 2, 2, 2)
(3, 6, 6, 2)
[[ 0.0169049  -0.51498352]
 [ 0.24450929 -0.18931261]]
[[0. 0.]
 [0. 0.]
 [0. 0.]
 [0. 0.]
 [0. 0.]
 [0. 0.]]
```

### 3.2 Convolutional Layer
So now we'll try implementing our own conv layer. It may seem very complicated, but try thinking about what each line of code actually DOES, and it will start coming together.

In [ ]:
def conv_single_step(a_slice_prev, W, b):
    #Element-wise product between a_slice, W
    s = None
    #Sum over all entries of volume s
    Z = None
    #Add bias b to Z. Cast b to a float()
    Z = None
    
    return Z

In [ ]:
np.random.seed(1)
a_slice_prev = np.random.randn(2, 2, 4)
W = np.random.randn(2, 2, 4)
b = np.random.randn(1, 1, 1)

Z = conv_single_step(a_slice_prev, W, b)
print("Z =", Z)

Your output should be:
```
Z = -1.7334289119940802
```

Next, we will try implementing a forward pass for the conv layer. Use the equations below to help you.

$$ nH = (nH\_prev - f + 2xpad) / stride + 1 $$
$$ nW = (nH\_prev - f + 2xpad) / stride + 1 $$

In [ ]:
def conv_forward(A_prev, W, b, stride = 2, pad = 2):
    
    #Get the dimensions of A_prev
    (m, n_H_prev, n_W_prev, n_C_prev) = None
    
    #Compute the dimensions using the formulas above
    n_H = None
    n_W = None
    
    #Get W's shape for parameters
    (f, f, n_C_prev, n_C) = None
    
    #Initialize an output shape
    Z = None
    
    #Padd the array
    A_prev_pad = None
    
    for i in range(m):
        a_prev_pad = None
        for h in range(n_H):
            for w in range(n_W):
                for c in range(n_C):
                    vert_start = None
                    vert_end = None
                    horiz_start = None
                    horiz_end = None
                    
                    a_slice_prev = None
                    
                    Z[i, h, w, c] = None
    
    cache = (A_prev, W, b)
    
    return Z, cache     

In [ ]:
np.random.seed(1)
A_prev = np.random.randn(10, 5, 5, 4)
W = np.random.randn(5, 5, 4, 2)
b = np.random.randn(1, 1, 1, 2)
Z, cache = conv_forward(A_prev, W, b)

print("Z's mean =", np.mean(Z))
print("Z[3,2,1] =", Z[3,2,1])
print("cache[2][0][1][9] =", cache[0][1][2][3])

Your output should be:
```
Z's mean = -1.424723284740757
Z[3,2,1] = [-8.39966421  4.78707002]
cache[2][0][1][9] = [ 1.0388246   2.18697965  0.44136444 -0.10015523]
```

## 4 Max Pool Layer
As you have read already, the max pool layer takes the maximum value of a window and stores it into a new volume of "max values". It basically shrinks the data to make it easier to calculate.
### 4.1 Building the Layer
You will use these 3 equations to build the max pool layer:

$$ nH = (nH\_prev - f) / stride + 1 $$
$$ nW = (nW\_prev - f) / stride + 1 $$
$$ nC = nC\_prev $$

In [ ]:
def max_pool_forwards(A_prev, stride = 2, f = 2):
    #Get the dimensions of A_prev
    (m, n_H_prev, n_W_prev, n_C_prev) = None
    
    #Compute the dimensons using the equations above
    n_H = None
    n_W = None
    n_C = None
    
    #Initialize the output matrix
    A = np.zeros((m, n_H, n_W, n_C))
    
    for i in range(m):
        for h in range(n_H):
            for w in range(n_W):
                for c in range(n_C):
                    #find the corners
                    vert_start = None
                    vert_end = None
                    horiz_start = None
                    horiz_end = None
                    
                    #create a slice for the ith training example
                    a_prev_slice = None
                    
                    #"pool" the slice (hint: use np.max)
                    A[i, h, w, c] = None
                    
    cache = (A_prev)
    return A, cache

In [ ]:
np.random.seed(2019)
A_prev = np.random.randn(3, 3, 3, 3) #(training examples, height, width, channels)

A, cache = max_pool_forwards(A_prev, stride=2, f=2)
print("A =", A)

Your output should be:
```
A = [[[[1.33186404 0.82145535 1.48127781]]]


 [[[0.48668927 0.58680631 1.07080136]]]


 [[[0.36062884 0.35325398 1.51572304]]]]
```

Max pooling backwards will be a lot more complicated, so we won't be going over that. However, as long as you get the concept of max pooling, you are on track.

## Congrats!
You've completed this assignment. Next, we will see how to build a convnet using tf keras.